#!/bin/bash
vol="$(amixer get Master | awk '$0~/%/{print $4}' | tr -d '[]')"
mute="$(amixer get Master | grep -o '\[on\|\[off' | awk '{print $1}')"
if [ "$mute" == "[off" ] 
then
	#amixer set Master mute > /dev/null
	echo "󰖁 " 
	exit
#else
	#amixer set Master unmute > /dev/null
	#amixer set Speaker unmute > /dev/null
	#amixer set Headphone unmute > /dev/null
fi
mute="$(amixer get Master | grep -o '\[on\|\[off' | awk '{print $1}')"
vol="${vol#Volume: }"
split() {
	# For ommiting the . without calling and external program.
	IFS=$2
	set -- "$1"
	printf '%s' "$@"
}
vol="$(split "$vol" "%")"
vol="${vol##0}"

case "$1" in
	$((vol >= 70)) ) icon=" " ;;
	$((vol >= 30)) ) icon="󰕾 " ;;
	$((vol >= 1)) ) icon=" " ;;
	$((vol = 0)) ) icon=" " ;;
	* ) echo   && exit ;;
esac

echo "$icon$vol"
