#!/bin/bash
darkFolder="/home/grigory/.local/share/backgrounds/dark/"
lightFolder="/home/grigory/.local/share/backgrounds/light/"

#default setting
option="light"

getopts ":dl" opt

case ${opt} in
  d )
    option="dark"
    ;;
  l )
    option="light"
    ;;
  \? )
    echo "Invalid option: -$OPTARG" 1>&2
    ;;
  : )
    echo "Option -$OPTARG requires an argument." 1>&2
    ;;
esac

if [ $option = "dark" ]
then
	randBackground=$(ls $darkFolder | sort -R | tail -1)
	echo "$darkFolder$randBackground"
	feh --bg-scale $darkFolder/$randBackground
else
	randBackground=$(ls $lightFolder | sort -R | tail -1)
	echo "$lightFolder$randBackground"
	feh --bg-scale $lightFolder/$randBackground
fi
